- name: Check etcd process
  shell: |
    pgrep -fa etcd

- name: Check etcd health
  shell: |
    . /etc/etcd/etcd.conf
    etcdctl --cert-file=/etc/etcd/peer.crt \
      --key-file=/etc/etcd/peer.key \
      --ca-file=/etc/etcd/ca.crt \
      --peers="$ETCD_ADVERTISE_CLIENT_URLS" \
    cluster-health

- name: Check nodes
  run_once: yes
  shell: |
    oc get nodes

