- name: Check etcd process
  shell: |
    pgrep -fa etcd
  check_mode: no
  changed_when: false

- name: Check etcd health
  shell: |
    . /etc/etcd/etcd.conf
    etcdctl --cert-file=/etc/etcd/peer.crt \
      --key-file=/etc/etcd/peer.key \
      --ca-file=/etc/etcd/ca.crt \
      --peers="$ETCD_ADVERTISE_CLIENT_URLS" \
    cluster-health
  check_mode: no
  register: etcd_cluster_health
  failed_when: "'cluster is healthy' not in etcd_cluster_health.stdout"
  changed_when: etcd_cluster_health.rc != 0
