#
# Various openshift checks
#
- include: etcd.yml
  when: >
    'etcd' in group_names

- include: rhn.yml

- include: masters.yml
  when: >
    'masters' in group_names

- include: nodes.yml
  when: >
    ocp_version != ""

- include: create_test_project.yml
  when:
  - create_test_project | default(false) | bool
  - >
    'masters' in group_names