- name: Subscription Manager is ok
  shell: >
    subscription-manager status
  register: subscription_manager_status
  failed_when: "'Overall Status: Current' not in subscription_manager_status.stdout"
  check_mode: no
  changed_when: false
